### ISSUE TITLE
Cucumber Framework - Error "Failed to instantiate class MyStepdefs" when using GenericDriver

### ISSUE THREAD

**Issue by gileli121** [testproject-io/java-opensdk#84]
**My code**

resources/Features/SomeFeatureTest.feature:
```feature
Feature: Feature Header
  Scenario: Scenario Header
    Given Given Header
    And And Header
    And And Header
    When When header
    Then Then Header
```

java/MyStepdefs.java:

```java
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.testproject.sdk.drivers.GenericDriver;
import io.testproject.sdk.internal.exceptions.AgentConnectException;
import io.testproject.sdk.internal.exceptions.InvalidTokenException;
import io.testproject.sdk.internal.exceptions.ObsoleteVersionException;

import java.io.IOException;

public class MyStepdefs {

    private final GenericDriver driver;
    public MyStepdefs() throws InvalidTokenException, AgentConnectException, ObsoleteVersionException, IOException {
        driver = new GenericDriver();
    }

    @Given("Given Header")
    public void given_header() {
        driver.report().step("Report: Step in Given Header");
    }

    @Given("And Header")
    public void and_header() {
        driver.report().step("Report: Step in And Header");
    }

    @When("When header")
    public void when_header() {
        driver.report().step("Report: Step in When Header");
    }

    @Then("Then Header")
    public void then_header() {
        driver.report().step("Report: Step in Then Header");
    }

}

```

**Issue**
When I execute the code, I get the following error:

```log
2021-02-10 14:56:15.190 TRACE AgentClient          Report settings were not provided or incomplete, trying to infer...
2021-02-10 14:56:15.191 INFO  AgentClient          Inferred [io.cucumber.core.cli] and [io.cucumber.core.cli.Main] for Project and Job names accordingly.
2021-02-10 14:56:15.192 INFO  AgentClient          Using [io.cucumber.core.cli] and [io.cucumber.core.cli.Main] for Project and Job names accordingly.
2021-02-10 14:56:15.192 INFO  AgentClient          Initializing new session...
2021-02-10 14:56:15.196 TRACE AgentClient          Initializing new session with capabilities: {"caps":{"platformName":"ANY","tp:guid":"7eb3db53-0bae-4300-b9d8-c9f0f3634145"}}
2021-02-10 14:56:18.138 TRACE AgentClient          Session initialization response: {"devSocketPort":20060,"serverAddress":"","version":"0.65.50"}
2021-02-10 14:56:18.139 INFO  AgentClient          Session [null] initialized
2021-02-10 14:56:18.141 TRACE SocketManager        Connecting to Agent socket: localhost:20060
2021-02-10 14:56:18.141 DEBUG SocketManager        Development socket connected

Step failed
io.cucumber.core.exception.CucumberException: Failed to instantiate class MyStepdefs
	at io.cucumber.core.runtime.ObjectFactoryServiceLoader$DefaultJavaObjectFactory.cacheNewInstance(ObjectFactoryServiceLoader.java:140)
	at io.cucumber.core.runtime.ObjectFactoryServiceLoader$DefaultJavaObjectFactory.getInstance(ObjectFactoryServiceLoader.java:124)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
	at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1598)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
	at io.cucumber.core.cli.Main.run(Main.java:92)
	at io.cucumber.core.cli.Main.main(Main.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at io.cucumber.core.runtime.ObjectFactoryServiceLoader$DefaultJavaObjectFactory.cacheNewInstance(ObjectFactoryServiceLoader.java:132)
	... 32 more
Caused by: java.lang.NullPointerException
	at io.testproject.sdk.internal.reporting.Reporter.disableTestAutoReports(Reporter.java:96)
	at io.testproject.sdk.internal.reporting.Reporter.<init>(Reporter.java:62)
	at io.testproject.sdk.drivers.GenericDriver.<init>(GenericDriver.java:274)
	at io.testproject.sdk.drivers.GenericDriver.<init>(GenericDriver.java:100)
	at io.testproject.sdk.drivers.GenericDriver.<init>(GenericDriver.java:77)
	at MyStepdefs.<init>(MyStepdefs.java:18)
	... 38 more

```

If you change `GenericDriver` to `ChromeDriver` it will work without errors

**Comment by DavidG8168** [comment]
Should be solved by this:
https://github.com/testproject-io/java-opensdk/pull/87
